---
apiVersion: v1
kind: Pod
metadata:
  namespace: hello
  name: busybox
spec:
  containers:
    - command:
        - sh
        - -c
        - echo The app is running! && sleep 1000
      image: busybox
      imagePullPolicy: IfNotPresent
      name: busybox-container
  initContainers:
    - command:
        - sh
        - -c
        - sleep 2;
      image: busybox
      imagePullPolicy: Always
      name: init-myservice

