---
apiVersion: v1
kind: Pod
metadata:
  name: orange
spec:
  containers:
    - command:
        - sh
        - -c
        - echo The app is running! && sleep 3600
      image: busybox
      imagePullPolicy: IfNotPresent
      name: orange-container
  initContainers:
    - command:
        - sh
        - -c
        - sleep 2;
      image: busybox
      imagePullPolicy: Always
      name: init-myservice
---
kind: Namespace
apiVersion: v1
metadata:
  name: finance
  labels:
    name: finance
