apiVersion: v1
kind: Pod
metadata:
  name: messaging-pod
  namespace: hello
  labels:
    tier: msg
spec:
  matchLabels:
    tier: msg
spec:
  containers:
    - name: redis-pod
      image: redis:alpine
      ports:
        - containerPort: 6379
      
