apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: hello
spec:
  containers:
    - name: nginx-pod
      image: nginx:alpine
      ports:
        - containerPort: 80
      
